apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: e-commerce
        image: e-commerce-backend-backend:latest 
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: PORT
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: SECRET_KEY
        - name: StripeAPIKey
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: StripeAPIKey

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
  

